// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(MovieWorskshopDbContext))]
    [Migration("20240826170244_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DomainModels.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 90,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8569),
                            Description = "A thrilling adventure into the unknown.",
                            Genre = 4,
                            ReleaseDate = new DateTime(2012, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Echo of Dreams",
                            Year = 2012
                        },
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8617),
                            Description = "An epic story of bravery and courage.",
                            Genre = 2,
                            ReleaseDate = new DateTime(2007, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mystery Unveiled",
                            Year = 2007
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8620),
                            Description = "A mysterious journey into the unknown.",
                            Genre = 7,
                            ReleaseDate = new DateTime(2015, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Journey Beyond",
                            Year = 2015
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8624),
                            Description = "A tale of love and loss.",
                            Genre = 5,
                            ReleaseDate = new DateTime(2018, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Love's Echo",
                            Year = 2018
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8626),
                            Description = "A gripping narrative that will keep you on the edge of your seat.",
                            Genre = 6,
                            ReleaseDate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Time Chronicles",
                            Year = 2020
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8630),
                            Description = "An epic tale of myth and legend.",
                            Genre = 9,
                            ReleaseDate = new DateTime(2013, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fallen Legends",
                            Year = 2013
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8632),
                            Description = "A journey to the edge of the world.",
                            Genre = 7,
                            ReleaseDate = new DateTime(2010, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last Frontier",
                            Year = 2010
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8633),
                            Description = "A spine-chilling tale of suspense.",
                            Genre = 11,
                            ReleaseDate = new DateTime(2019, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Haunting Shadows",
                            Year = 2019
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8636),
                            Description = "A story of dreams and aspirations.",
                            Genre = 12,
                            ReleaseDate = new DateTime(2016, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rising Stars",
                            Year = 2016
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8639),
                            Description = "An adventure into an ancient world.",
                            Genre = 4,
                            ReleaseDate = new DateTime(2011, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Forgotten Realm",
                            Year = 2011
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8641),
                            Description = "A dark thriller that will keep you guessing.",
                            Genre = 2,
                            ReleaseDate = new DateTime(2014, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Eternal Night",
                            Year = 2014
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8643),
                            Description = "A story of wild adventures and untamed spirits.",
                            Genre = 3,
                            ReleaseDate = new DateTime(2021, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wild Hearts",
                            Year = 2021
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8645),
                            Description = "A touching tale of romance and heartache.",
                            Genre = 5,
                            ReleaseDate = new DateTime(2008, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Love's Journey",
                            Year = 2008
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8647),
                            Description = "A futuristic vision of technology and society.",
                            Genre = 6,
                            ReleaseDate = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Techno Dreams",
                            Year = 2022
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8649),
                            Description = "A story about love and friendship.",
                            Genre = 3,
                            ReleaseDate = new DateTime(2017, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Broken Hearts Club",
                            Year = 2017
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8652),
                            Description = "A high-octane action film.",
                            Genre = 9,
                            ReleaseDate = new DateTime(2019, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Action Heroes",
                            Year = 2019
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8655),
                            Description = "A drama set against the backdrop of a bustling city.",
                            Genre = 1,
                            ReleaseDate = new DateTime(2018, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "City Lights",
                            Year = 2018
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8659),
                            Description = "A tale of ancient prophecies and forgotten lands.",
                            Genre = 4,
                            ReleaseDate = new DateTime(2010, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ancient Prophecies",
                            Year = 2010
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8661),
                            Description = "An exploration of mystical lands and hidden secrets.",
                            Genre = 7,
                            ReleaseDate = new DateTime(2016, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mystic Lands",
                            Year = 2016
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8663),
                            Description = "A magical tale of dreamers and their dreams.",
                            Genre = 4,
                            ReleaseDate = new DateTime(2014, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dreamweavers",
                            Year = 2014
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8665),
                            Description = "A chilling horror story with unexpected twists.",
                            Genre = 11,
                            ReleaseDate = new DateTime(2011, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Haunting",
                            Year = 2011
                        },
                        new
                        {
                            Id = 21,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8667),
                            Description = "An adventurous journey through uncharted territories.",
                            Genre = 7,
                            ReleaseDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Uncharted Paths",
                            Year = 2022
                        },
                        new
                        {
                            Id = 22,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8670),
                            Description = "A drama about the pursuit of dreams in a vibrant city.",
                            Genre = 1,
                            ReleaseDate = new DateTime(2017, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "City of Dreams",
                            Year = 2017
                        },
                        new
                        {
                            Id = 23,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8672),
                            Description = "A sci-fi epic exploring the final frontiers of space.",
                            Genre = 6,
                            ReleaseDate = new DateTime(2015, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Final Frontier",
                            Year = 2015
                        },
                        new
                        {
                            Id = 24,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8674),
                            Description = "A historical drama that uncovers echoes of the past.",
                            Genre = 1,
                            ReleaseDate = new DateTime(2021, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Echoes of the Past",
                            Year = 2021
                        },
                        new
                        {
                            Id = 25,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8676),
                            Description = "A comedic drama filled with laughter and tears.",
                            Genre = 3,
                            ReleaseDate = new DateTime(2013, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Laughs and Tears",
                            Year = 2013
                        },
                        new
                        {
                            Id = 26,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8678),
                            Description = "A horror film that brings nightmares to life.",
                            Genre = 11,
                            ReleaseDate = new DateTime(2020, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Horror Unleashed",
                            Year = 2020
                        },
                        new
                        {
                            Id = 27,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8680),
                            Description = "A science fiction saga set among the stars.",
                            Genre = 6,
                            ReleaseDate = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Voyagers",
                            Year = 2019
                        },
                        new
                        {
                            Id = 28,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8682),
                            Description = "An adventurous quest in a lost world.",
                            Genre = 7,
                            ReleaseDate = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lost World",
                            Year = 2023
                        },
                        new
                        {
                            Id = 29,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8684),
                            Description = "A classic tale of a hero's journey and personal growth.",
                            Genre = 9,
                            ReleaseDate = new DateTime(2018, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hero's Journey",
                            Year = 2018
                        },
                        new
                        {
                            Id = 30,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8686),
                            Description = "A romantic musical that captures the dance of love.",
                            Genre = 12,
                            ReleaseDate = new DateTime(2012, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dance of Hearts",
                            Year = 2012
                        },
                        new
                        {
                            Id = 31,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8688),
                            Description = "A fantasy film based on old legends and tales.",
                            Genre = 4,
                            ReleaseDate = new DateTime(2015, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tales of Old",
                            Year = 2015
                        },
                        new
                        {
                            Id = 32,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8690),
                            Description = "A high-stakes action thriller.",
                            Genre = 9,
                            ReleaseDate = new DateTime(2014, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Great Escape",
                            Year = 2014
                        },
                        new
                        {
                            Id = 33,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8692),
                            Description = "A touching drama about love and relationships.",
                            Genre = 1,
                            ReleaseDate = new DateTime(2017, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Heartstrings",
                            Year = 2017
                        },
                        new
                        {
                            Id = 34,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8694),
                            Description = "A thrilling science fiction adventure.",
                            Genre = 6,
                            ReleaseDate = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Alien Invasion",
                            Year = 2021
                        },
                        new
                        {
                            Id = 35,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8696),
                            Description = "An adventurous journey into the wilderness.",
                            Genre = 7,
                            ReleaseDate = new DateTime(2020, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wilderness Quest",
                            Year = 2020
                        },
                        new
                        {
                            Id = 36,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8698),
                            Description = "A dramatic tale set in the dawn of a new era.",
                            Genre = 1,
                            ReleaseDate = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rising Sun",
                            Year = 2023
                        },
                        new
                        {
                            Id = 37,
                            CreatedOn = new DateTime(2024, 8, 26, 19, 2, 44, 486, DateTimeKind.Local).AddTicks(8700),
                            Description = "A hilarious comedy about misunderstandings and mishaps.",
                            Genre = 3,
                            ReleaseDate = new DateTime(2018, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Comedy of Errors",
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
