// <auto-generated />
using System;
using Data_Access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Access.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20240822184936_AddedSeedingBackbecauseICantBeBothered")]
    partial class AddedSeedingBackbecauseICantBeBothered
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DomainModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModiefiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3472),
                            Description = "A wearable device that combines fitness tracking, smartphone notifications, and various apps in a compact form.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3501),
                            Name = "Smartwatch"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3510),
                            Description = "Compact, wireless in-ear headphones offering high-quality audio and noise cancellation features.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3512),
                            Name = "Wireless Earbuds"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3514),
                            Description = "High-performance portable computer optimized for gaming, featuring powerful processors, GPUs, and high refresh rate displays.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3516),
                            Name = "Gaming Laptop"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3518),
                            Description = "A display screen offering ultra-high-definition resolution for sharper, more detailed visuals in gaming, work, or media.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3520),
                            Name = "4K Monitor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3523),
                            Description = "A head-mounted device that immerses users in a 3D virtual environment for gaming, simulations, and entertainment.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3524),
                            Name = "Virtual Reality Headset"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3529),
                            Description = "A portable solid-state drive offering fast data transfer speeds and robust storage for files, games, and media.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3530),
                            Name = "External SSD"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3532),
                            Description = "A central device that connects and controls various smart home products like lights, thermostats, and security systems.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3534),
                            Name = "Smart Home Hub"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3536),
                            Description = "A wireless speaker that connects to devices via Bluetooth, providing portable, high-quality sound for music and calls.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3538),
                            Name = "Bluetooth Speaker"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3540),
                            Description = "An unmanned aerial vehicle equipped with a high-resolution camera for capturing aerial photos and videos.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3541),
                            Name = "Drone with Camera"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3544),
                            Description = "A programmable thermostat that adjusts heating and cooling based on user preferences and can be controlled remotely.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3546),
                            Name = "Smart Thermostat"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3548),
                            Description = "A portable device designed for reading digital books and magazines, featuring a paper-like display and long battery life.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3550),
                            Name = "E-Reader"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3552),
                            Description = "A device that charges smartphones and other gadgets wirelessly through inductive charging technology.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3553),
                            Name = "Wireless Charging Pad"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3555),
                            Description = "A wearable device that monitors physical activity, heart rate, sleep patterns, and other health metrics.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3557),
                            Name = "Fitness Tracker"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3559),
                            Description = "A surveillance camera system that provides real-time monitoring and alerts to enhance home security.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3561),
                            Name = "Home Security Camera"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3563),
                            Description = "Headphones that reduce ambient noise, providing an immersive audio experience for music and calls.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3564),
                            Name = "Noise-Cancelling Headphones"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3566),
                            Description = "An energy-efficient light bulb that can be controlled remotely, with options for color and brightness adjustments.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3568),
                            Name = "Smart Light Bulb"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3570),
                            Description = "A compact, rechargeable battery pack used to charge smartphones, tablets, and other devices on the go.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3572),
                            Name = "Portable Power Bank"
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3575),
                            Description = "An autonomous vacuum cleaner that navigates and cleans floors with minimal user input.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3576),
                            Name = "Robot Vacuum Cleaner"
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3578),
                            Description = "A machine that creates three-dimensional objects by layering material based on digital models.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3580),
                            Name = "3D Printer"
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3582),
                            Description = "A doorbell with an integrated camera that allows users to see and communicate with visitors remotely.",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3584),
                            Name = "Smart Doorbell"
                        });
                });

            modelBuilder.Entity("DomainModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModiefiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3613),
                            Description = "The latest smartwatch with advanced fitness tracking and seamless iPhone integration.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3615),
                            Name = "Apple Watch Series 7",
                            Price = 399.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3630),
                            Description = "Premium wireless earbuds with industry-leading noise cancellation.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3631),
                            Name = "Sony WF-1000XM4",
                            Price = 279.99m,
                            StockQuantity = 66
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3634),
                            Description = "A powerful gaming laptop with AMD Ryzen 9 processor and RTX 3060 graphics.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3636),
                            Name = "ASUS ROG Zephyrus G14",
                            Price = 1499.99m,
                            StockQuantity = 23
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3639),
                            Description = "A 27-inch monitor with stunning 4K resolution and ultra-thin bezels.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3640),
                            Name = "Dell UltraSharp 27 4K Monitor",
                            Price = 699.99m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3643),
                            Description = "A standalone VR headset offering an immersive gaming experience without needing a PC.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3645),
                            Name = "Oculus Quest 2",
                            Price = 299.99m,
                            StockQuantity = 94
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3649),
                            Description = "A fast and durable external SSD with up to 1TB of storage.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3650),
                            Name = "Samsung T7 Portable SSD",
                            Price = 169.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3653),
                            Description = "A smart display that connects and controls your smart home devices with a rotating screen.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3655),
                            Name = "Amazon Echo Show 10",
                            Price = 249.99m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3658),
                            Description = "A waterproof Bluetooth speaker offering powerful sound in a portable form.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3659),
                            Name = "JBL Flip 5",
                            Price = 119.99m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3662),
                            Description = "A compact drone with a 4K camera and intelligent flight modes.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3664),
                            Name = "DJI Mavic Air 2",
                            Price = 799.99m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3668),
                            Description = "A smart thermostat that learns your schedule and programs itself to save energy.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3669),
                            Name = "Nest Learning Thermostat",
                            Price = 249.99m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 11,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3672),
                            Description = "An e-reader with a high-resolution display and built-in adjustable light.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3674),
                            Name = "Kindle Paperwhite",
                            Price = 129.99m,
                            StockQuantity = 27
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 12,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3677),
                            Description = "A sleek and efficient wireless charger compatible with Qi-enabled devices.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3678),
                            Name = "Anker Wireless Charging Pad",
                            Price = 29.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 13,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3681),
                            Description = "An advanced fitness tracker with built-in GPS, heart rate monitoring, and stress management tools.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3683),
                            Name = "Fitbit Charge 5",
                            Price = 179.99m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 14,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3686),
                            Description = "A wire-free security camera with 2K video resolution and color night vision.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3687),
                            Name = "Arlo Pro 4 Security Camera",
                            Price = 199.99m,
                            StockQuantity = 94
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 15,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3690),
                            Description = "Over-ear headphones with exceptional noise cancellation and premium sound quality.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3692),
                            Name = "Bose QuietComfort 45",
                            Price = 329.99m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 16,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3695),
                            Description = "A color-changing smart light bulb that can be controlled via app or voice commands.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3696),
                            Name = "Philips Hue Smart Bulb",
                            Price = 49.99m,
                            StockQuantity = 23
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 17,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3699),
                            Description = "A compact and powerful power bank capable of charging your devices multiple times.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3700),
                            Name = "Anker PowerCore 10000",
                            Price = 39.99m,
                            StockQuantity = 98
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 18,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3704),
                            Description = "A smart vacuum cleaner that empties itself and can be scheduled for automatic cleaning.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3706),
                            Name = "iRobot Roomba i7+",
                            Price = 599.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 19,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3709),
                            Description = "An affordable and reliable 3D printer for beginners and hobbyists.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3711),
                            Name = "Creality Ender 3 V2",
                            Price = 259.99m,
                            StockQuantity = 79
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 20,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3714),
                            Description = "A video doorbell with 3D motion detection and enhanced video quality.",
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3715),
                            Name = "Ring Video Doorbell Pro 2",
                            Price = 249.99m,
                            StockQuantity = 62
                        });
                });

            modelBuilder.Entity("DomainModels.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModiefiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "The Apple Watch Series 7 has been a game-changer for tracking my workouts.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3744),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3746),
                            ProductId = 1,
                            Rating = 5,
                            ReviewerName = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "The noise cancellation on the Sony WF-1000XM4 is amazing. Perfect for commuting!",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3752),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3754),
                            ProductId = 2,
                            Rating = 1,
                            ReviewerName = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "The ASUS ROG Zephyrus G14 runs all my games smoothly. Best gaming laptop I've owned!",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3757),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3758),
                            ProductId = 3,
                            Rating = 5,
                            ReviewerName = "Alex Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "The Dell UltraSharp 27 4K Monitor has stunning visuals, perfect for my design work.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3761),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3762),
                            ProductId = 4,
                            Rating = 4,
                            ReviewerName = "Emily Brown"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "The Oculus Quest 2 is incredibly immersive. My favorite VR headset so far.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3765),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3767),
                            ProductId = 5,
                            Rating = 1,
                            ReviewerName = "Michael Davis"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "The Samsung T7 Portable SSD is super fast. Makes transferring files a breeze.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3770),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3772),
                            ProductId = 6,
                            Rating = 1,
                            ReviewerName = "Sarah Wilson"
                        },
                        new
                        {
                            Id = 7,
                            Comment = "The Echo Show 10 is a great smart home hub. The rotating screen is very handy.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3775),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3776),
                            ProductId = 7,
                            Rating = 1,
                            ReviewerName = "Chris Martinez"
                        },
                        new
                        {
                            Id = 8,
                            Comment = "The JBL Flip 5 delivers excellent sound quality, especially for its size.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3867),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3871),
                            ProductId = 8,
                            Rating = 5,
                            ReviewerName = "Jessica Taylor"
                        },
                        new
                        {
                            Id = 9,
                            Comment = "The DJI Mavic Air 2 captures stunning aerial footage. Easy to fly as well.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3876),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3878),
                            ProductId = 9,
                            Rating = 3,
                            ReviewerName = "Daniel Anderson"
                        },
                        new
                        {
                            Id = 10,
                            Comment = "The Nest Learning Thermostat saved me on energy bills. Love the automation features.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3883),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3885),
                            ProductId = 10,
                            Rating = 2,
                            ReviewerName = "Sophia Thomas"
                        },
                        new
                        {
                            Id = 11,
                            Comment = "The Kindle Paperwhite is perfect for reading on the go. The screen is very clear.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3888),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3889),
                            ProductId = 11,
                            Rating = 2,
                            ReviewerName = "David Jackson"
                        },
                        new
                        {
                            Id = 12,
                            Comment = "The Anker Wireless Charging Pad is a convenient way to charge my phone. Works great.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3892),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3893),
                            ProductId = 12,
                            Rating = 4,
                            ReviewerName = "Olivia Moore"
                        },
                        new
                        {
                            Id = 13,
                            Comment = "The Fitbit Charge 5 has helped me stay on top of my fitness goals. Love the new features.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3896),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3898),
                            ProductId = 13,
                            Rating = 4,
                            ReviewerName = "Liam Harris"
                        },
                        new
                        {
                            Id = 14,
                            Comment = "The Arlo Pro 4 Security Camera gives me peace of mind. Easy to set up and use.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3900),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3902),
                            ProductId = 14,
                            Rating = 1,
                            ReviewerName = "Ava Martinez"
                        },
                        new
                        {
                            Id = 15,
                            Comment = "The Bose QuietComfort 45 are the best noise-cancelling headphones I've tried.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3905),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3907),
                            ProductId = 15,
                            Rating = 3,
                            ReviewerName = "Noah Robinson"
                        },
                        new
                        {
                            Id = 16,
                            Comment = "The Philips Hue Smart Bulb adds a lot of ambiance to my room. The color options are great.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3909),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3911),
                            ProductId = 16,
                            Rating = 5,
                            ReviewerName = "Isabella Clark"
                        },
                        new
                        {
                            Id = 17,
                            Comment = "The Anker PowerCore 10000 is a lifesaver on long trips. Charges my devices multiple times.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3914),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3915),
                            ProductId = 17,
                            Rating = 4,
                            ReviewerName = "Mason Rodriguez"
                        },
                        new
                        {
                            Id = 18,
                            Comment = "The iRobot Roomba i7+ keeps my floors clean without any effort. I love the self-emptying feature.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3919),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3920),
                            ProductId = 18,
                            Rating = 3,
                            ReviewerName = "Mia Lewis"
                        },
                        new
                        {
                            Id = 19,
                            Comment = "The Creality Ender 3 V2 is perfect for my 3D printing projects. Easy to assemble and use.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3923),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3925),
                            ProductId = 19,
                            Rating = 3,
                            ReviewerName = "Ethan Walker"
                        },
                        new
                        {
                            Id = 20,
                            Comment = "The Ring Video Doorbell Pro 2 offers clear video and great motion detection. A must-have for home security.",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3927),
                            ImageUrl = "",
                            ModiefiedBy = 1,
                            ModifiedOn = new DateTime(2024, 8, 22, 20, 49, 35, 774, DateTimeKind.Local).AddTicks(3929),
                            ProductId = 20,
                            Rating = 2,
                            ReviewerName = "Charlotte Hill"
                        });
                });

            modelBuilder.Entity("DomainModels.Product", b =>
                {
                    b.HasOne("DomainModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DomainModels.Review", b =>
                {
                    b.HasOne("DomainModels.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DomainModels.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DomainModels.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
